# --- GRUPOS PARA TU ORQUESTACIÓN MAESTRA ---
[debian_ubuntu_nodes]
deb1 ansible_host=192.168.2.26
deb2 ansible_host=192.168.2.28
ubun1 ansible_host=192.168.2.27
ubun2 ansible_host=192.168.2.29

[rhel_nodes]
# Agrega aquí tus nodos RHEL cuando los tengas
# ejemplo: rhel1 ansible_host=192.168.2.X

[proxmox_nodes]
# Agrega aquí tus nodos de Proxmox

[win10_nodes]
# Agrega aquí tus nodos Windows 10
dev1 ansible_host=192.168.2.22
dev2 ansible_host=192.168.2.23

[win2025_nodes]
# Agrega aquí tus nodos Windows Server 2025
app1 ansible_host=192.168.2.24
app2 ansible_host=192.168.2.25

# --- VARIABLES GLOBALES ---
[all:vars]
ansible_user=tu_usuario
# Si necesitas autenticación específica para Windows, 
# se suelen definir variables de grupo por separado.
